spring:
  datasource:
    url: jdbc:postgresql://database-1.cmtm4w2q8rts.ap-northeast-2.rds.amazonaws.com:5432/nova
    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: test1212
    username: ENC(IDdd/EqGT8hyHUX7chZTOQ9BbJfnWbm7)
    password: ENC(IgFTdDFO/Wqr7UamoziAnhsIEAIXDk6p)
